# -*- coding: utf-8 -*-
"""credit card fraud  detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18bi1YJ8jo05_gGVoI3I_dNrYcc7LkA_-

#Import library and derive dataset from kaggle
"""

import kagglehub
path = kagglehub.dataset_download("mlg-ulb/creditcardfraud")
import os
import pandas as pd
path_df=os.path.join(path,"creditcard.csv")

df=pd.read_csv(path_df)
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df.head()

"""#checking missing value whether present or not"""

df.isnull().sum()

sns.heatmap(df.isnull().sum().to_frame())

df.describe()

"""#checking datatype"""

df.info()

"""#classification of data into two parts
binary classification

1. legit
2. fraud


"""

df['Class'].value_counts()

legit=df[df.Class==0]
fraud=df[df.Class==1]

legit

legit.Amount.describe()

fraud.Amount.describe()

df.groupby('Class').mean()

"""#checking dataset is balence or imbalence"""

legit.shape,fraud.shape

"""#handling imbalance datset"""

legit_sample=legit.sample(n=492)

legit_sample

fraud

new_dataset=pd.concat([legit_sample,fraud],axis=0)

new_dataset

"""#splitting data into two parts"""

y=new_dataset['Class']
x=new_dataset.drop(columns='Class',axis=1)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=43)

x_train.shape,x_test.shape,y_train.shape,y_test.shape

from sklearn.linear_model import LogisticRegression

lr=LogisticRegression()

lr.fit(x_train, y_train)

y_pred=lr.predict(x_test)
dataset=pd.DataFrame({'Actual':y_test,'Predicted':y_pred})
dataset

new_dataset.columns

"""#accuracy test"""

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score

accuracy_score(y_test,lr.predict(x_test))

confusion_matrix(y_test,lr.predict(x_test))

classification_report(y_test,lr.predict(x_test))

recall_score(y_test,lr.predict(x_test))

precision_score(y_test,lr.predict(x_test))

f1_score(y_test,lr.predict(x_test))

new_dataset

"""#Data viualization"""

legit=new_dataset[new_dataset.Class==0]
fraud=new_dataset[new_dataset.Class==1]

sns.countplot(x='Class',data=new_dataset)

sns.lineplot(x='Class',y='Amount',data=new_dataset)

sns.catplot(x='Class',y='Amount',data=new_dataset,kind='box')
#

sns.scatterplot(x='Class',y='Amount',data=new_dataset)

sns.histplot(x='Class',y='Amount',data=new_dataset)

plt.figure(figsize=(15,15))
sns.heatmap(new_dataset.corr(),annot=True)
plt.show()

